ports:
  - 21
  - 22
  - 23
  - 80
  - 110
  - 135
  - 136
  - 137
  - 138
  - 139
  - 143
  - 445
  - 993
  - 995
  - 3306
  - 3389
  - 5900
  - 6379
  - 27017
  - 5060
  - 8080
max_connections: 100
log_path: "gopot.log"
banners:
  "21": "220 ProFTPD Server ready.\r\n"
  "22": "SSH-2.0-OpenSSH_8.2p1 Ubuntu-4ubuntu0.1\r\n"
  "23": "Welcome to Microsoft Telnet Service\r\n"
  "80": "HTTP/1.1 404 Not Found\r\nServer: Apache/2.4.29 (Ubuntu)\r\nContent-Length: 0\r\n\r\n"
  "110": "+OK POP3 server ready\r\n"
  "135": "Microsoft Windows RPC Service ready\r\n"
  "136": "Microsoft Windows RPC Service ready\r\n"
  "137": "Microsoft Windows NetBIOS Name Service ready\r\n"
  "138": "Microsoft Windows NetBIOS Datagram Service ready\r\n"
  "139": "Microsoft Windows NetBIOS Session Service ready\r\n"
  "143": "+OK IMAP4rev1 server ready\r\n"
  "445": "Microsoft Windows SMB Service ready\r\n"
  "993": "+OK IMAP4rev1 server ready (SSL)\r\n"
  "995": "+OK POP3 server ready (SSL)\r\n"
  "3306": "5.7.42 MySQL Community Server (GPL)\r\n"
  "3389": "Microsoft Terminal Services ready\r\n"
  "5900": "RFB 003.008\r\n"
  "6379": "+PONG\r\n"
  "27017": "MongoDB server ready\r\n"
  "5060": "SIP/2.0 200 OK\r\n"
  "8080": "HTTP/1.1 404 Not Found\r\nServer: Apache/2.4.29 (Ubuntu)\r\nContent-Length: 0\r\n\r\n"
